name: Tests CI/CD

on: ["push"]

env: 
 DATABASE_NAME: "test"

jobs:
  dummy-job:
    strategy:
      matrix:
       version: [14, 16, 18]
       os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: "my job"
    runs-on:  ${{matrix.os}}
    steps:
      - run: ls -la
      # on récupère le contenu du dépôt
      - uses: actions/checkout@v3
      - run: ls -la
      - name: "Installation de node"
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.version}}
      - run: node -v
      - run: echo ${{github.actor}} ${{github.event_name}}
      - run: node dummy.js
        env: 
          DATABASE_NAME: 'override du database'